# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 12:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('astorcore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basepage',
            name='published_page',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='base_page', to='astorcore.BasePage'),
        ),
    ]
