# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 22:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astorcore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagevisit',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
