# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 23:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('astorcore', '0002_auto_20170127_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rootpage',
            name='owner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='root_page', to=settings.AUTH_USER_MODEL),
        ),
    ]
