# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astorcore', '0002_auto_20170212_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentpage',
            name='abstract',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='contentpage',
            name='body',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='indexpage',
            name='abstract',
            field=models.TextField(blank=True, default=''),
        ),
    ]
