# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 22:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astorcore', '0003_auto_20170306_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagevisit',
            name='request_method',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='pagevisit',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
    ]
