# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 23:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('astorcore', '0005_auto_20170306_2302'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pagevisit',
            unique_together=set([('page', 'ip_address', 'timestamp')]),
        ),
    ]
