# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 23:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('astorcore', '0005_basepage_comments_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='astorcore.BasePage'),
        ),
    ]
