# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 23:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('astorcore', '0006_auto_20170306_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagevisit',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, unique_for_month='timestamp'),
        ),
        migrations.AlterField(
            model_name='pagevisit',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='astorcore.Page', unique_for_month='timestamp'),
        ),
        migrations.AlterUniqueTogether(
            name='pagevisit',
            unique_together=set([('page', 'ip_address')]),
        ),
    ]
