# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 23:12
from __future__ import unicode_literals

import astorcore.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('astorcore', '0007_auto_20170218_2342'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadPage',
            fields=[
                ('basepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='astorcore.BasePage')),
                ('abstract', models.TextField(blank=True, default='')),
                ('file', models.FileField(upload_to=astorcore.utils.user_directory_path)),
            ],
            bases=('astorcore.basepage',),
        ),
        migrations.CreateModel(
            name='ExternalHTMLPage',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('astorcore.uploadpage',),
        ),
    ]
