# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 21:35
from __future__ import unicode_literals

import astorcore.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astorcore', '0010_auto_20170301_2059'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageVisit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='htmluploadpage',
            name='file',
            field=models.FileField(upload_to=astorcore.utils.user_directory_path),
        ),
    ]
